name: toogym
description: GymFlow Pro - Gym Management SaaS
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.6.1

  # Routing
  go_router: ^15.1.2

  # HTTP
  dio: ^5.8.0+1

  # Local storage
  shared_preferences: ^2.5.3

  # JSON / immutable models
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Utilities
  intl: ^0.20.2

  # Icons
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Code generation
  build_runner: ^2.4.15
  freezed: ^2.5.7
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true